### ISSUE TITLE
 connection refused after running docker with sysbox-runc

### ISSUE THREAD

**Issue by jclaveau** [nestybox/sysbox-external#35]
I'm on Ubuntu 19.10 and installed without issue the bionic .deb.
Now, when I run `docker run --runtime=sysbox-runc ...` I get the following: 

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:364: starting container process caused "process_linux.go:474: container init caused \"process_linux.go:441: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2020-02-01T13:15:25+01:00\\\\\\\" level=fatal msg=\\\\\\\"dial unix /var/run/docker/libnetwork/b1aea14fa6b47a6f800f04a76d29b6fab16f9a9176a9c5a3a7a0259f801457ed.sock: connect: connection refused\\\\\\\"\\\\n\\\"\"": unknown.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Then docker doesn't work anymore at all (even with the default runtime) and `service` command neither:
```
sudo service docker restart
Failed to connect to bus: Connection refused
sudo service apache2 restart
Failed to connect to bus: Connection refused
```

The only way to get things up is to restart the computer.

Btw, while installing the deb, a `sudo service docker restart` was required for docker to detect the new runtime. This is missing in your docs.

**Comment by rodnymolina** [comment]
Jean, thanks for trying Sysbox and submitting this issue.

We don't support Ubuntu-Eoan just yet (see our supported releases [here](https://github.com/nestybox/sysbox-external#supported-linux-distros). Technically speaking, we are expecting Sysbox to work there, it's just that we haven't iterated through our validation/testing cycle to claim full support for it, and that's why there's no Ubuntu-Eoan image yet.

We are planning to extend full support for Ubuntu-Eoan in our next release.  In the meantime you can try Sysbox in any of our supported distros.

Let us know if any question.

Thanks.

**Comment by ctalledo** [comment]
Thanks Jean for filing the issue. Regarding:

> Btw, while installing the deb, a sudo service docker restart was required for docker to detect the new runtime. This is missing in your docs.

The Sysbox installer automatically configures Docker to detect the new runtime (by placing an entry in the `/etc/docker/daemon.json` and signaling the Docker engine to read it). But it's possible that the Sysbox installer is failing to do this on Ubuntu-Eoan, since we don't yet support it.

**Comment by rodnymolina** [comment]
Hi Jean,

Just to let you know that we have just published a new release ([v0.1.3](https://github.com/nestybox/sysbox-external/releases)) to extend Sysbox's support to Ubuntu Eoan. Please let us know if see any other issue or have any question for us.

Thanks.

**Comment by rodnymolina** [comment]
Observed behavior has been explained and new release has been created to prevent this issue from reoccurring. Closing issue now.

**Comment by jclaveau** [comment]
Thank you!
